### ISSUE TITLE
Tests fail on PHP 8

### ISSUE THREAD

**Issue by sstur** [sstur/js2php#12]
I'm not sure why, but [this test](https://github.com/sstur/js2php/blob/d7ea673b1da88f33d1e6e6b0d23dd4423a108de4/test/number.js#L37) seems to fail.

**Comment by imme64** [comment]
As described in https://wiki.php.net/rfc/string_to_number_comparison the semantics of the string to number comparison have changed in PHP 8.0. Before strings were converted to numbers and then number comparison was done (which led to 0 == "foo"). Now number comparison is only done if both strings are really numbers otherwise the number is converted to string and a string comparison is done.

The following table is taken from the linked RFC and the JavaScript column is added.
| Comparison | PHP < 8.0 | PHP >= 8.0 | JavaScript |
| -----------| -----------| -------- | ----- |
|  0 == "0"     | true   | true |  true |
|  0 == "0.0"   | true   | true | true |
|  0 == "foo"   | true   | false | false |
|  0 == ""      | true   | false | true |
| 42 == "   42" | true   | true | true |
| 42 == "42foo" | true   | false | false |
| "0" == "0.0" | true | true | false |
| "0" == "foo" | false | false | false |
| "0" == "" | false | false | false |
| "42" == "   42"  | true | true | false |
| "42" == "42foo" | false | false | false |
| 2 < 'a' | false | true | false |
| '2' < 'a' | true | true | true |
| 2 < '12' | true | true | true |
| '2' < '12' | true | true | false |

**Comment by imme64** [comment]
As described in https://wiki.php.net/rfc/string_to_number_comparison the semantics of the string to number comparison have changed in PHP 8.0. Before strings were converted to numbers and then number comparison was done (which led to 0 == "foo"). Now number comparison is only done if both strings are really numbers otherwise the number is converted to string and a string comparison is done.

The following table is based on the table from the linked RFC and the JavaScript column is added.
| Comparison | PHP < 8.0 | PHP >= 8.0 | JavaScript |
| -----------| -----------| -------- | ----- |
|  0 == "0"     | true   | true |  true |
|  0 == "0.0"   | true   | true | true |
|  0 == "foo"   | true   | false | false |
|  0 == ""      | true   | false | true |
| 42 == "   42" | true   | true | true |
| 42 == "42foo" | true   | false | false |
| 100 == "1e2" | true | true | true |
| "0" == "0.0" | true | true | false |
| "0" == "foo" | false | false | false |
| "0" == "" | false | false | false |
| "42" == "   42"  | true | true | false |
| "42" == "42foo" | false | false | false |
| "100" == "1e2" | true | true | false |
| 2 < 'a' | false | true | false |
| '2' < 'a' | true | true | true |
| 2 < '12' | true | true | true |
| '2' < '12' | true | true | false |
| 41 < '42foo' | true | true | false |
| '41' < '42foo' | true | true | true |

As you can see, the JavaScript semantics match neither the new nor the old PHP semantics. I guess that we need to implement all non-strict comparison operators `==, !=, >, >=, <, and <=` as we already do with `==` (which is very bad regarding performance but unavoidable regarding correctness).

The worst thing is that the non-strict comparison is also used in switch statements:
```
switch ("a") {
    case 0:
        console.log("0");
        break;
    case "a":
        console.log("a");
        break;
}
```
This will output `a` for JavaScript. 
```
<?php
switch ("a") {
    case 0:
        echo "0";
        break;
    case "a":
        echo "a";
        break;
}
```
For PHP 8, the output is `a` whereas PHP < 8 outputs `0`.

That means that to achieve correctness we cannot even use native switch statements. This also applies to functions like `in_array(), array_search() or array_keys()` and several sort functions (when used with `$sort_flags` set to `SORT_REGULAR` which is the default). But as far as I could see, we're not using any of those in our runtime code (only `asort()` but with `$sort_flags` set to `SORT_STRING`).

**Comment by sstur** [comment]
Wow, I did not know this about PHP 8. Thanks for the incredible detail here.

Now that I've read this it seems we're in a situation with no good options. From what I can tell the breaking change was done in such a way that there's no opt-in _or_ opt-out from within source-code, neither at the project or file level (i.e. they didn't do something like JavaScript's "use strict" for breaking changes). Since there's no way to emit code that opts out of this new behavior, it appears the only options are to:
- branch at run-time and/or re-implement all loose equality and comparator operators, and, as you pointed out, avoid emitting `switch` _and_ refrain from using certain helpers. This results in both perf regressions and uglier code.
- emit the worse-performing/uglier code mentioned above _only_ if a compile-time flag is set to `--support-php8`
- Explicitly choose to not support php8 (should document this and check/throw at runtime)

**Comment by imme64** [comment]
I fixed the issue without completely destroying readability and performance. I decided against using a compile-time flag because it would have made things way more complicated for me ;-).
