### ISSUE TITLE
API usage example?

### ISSUE THREAD

**Issue by bfred-it** [sstur/js2php#2]
Can you post some examples on how to use it within a node app? I was hoping to have it replace `js2php` but it doesn't look like the api is the same

**Comment by sstur** [comment]
Which `js2php` are you trying to replace? Do you have a link?

Granted, I should post some examples. Not sure when I can get to that but if I can understand your use case I might be able to quickly help...

**Comment by bfred-it** [comment]
Ah, sure, I assumed this repo was just called jstophp like on npm. It's this: https://www.npmjs.com/package/js2php

That lib has some issues with things like `variable[1]` (where `1` has to be a string to work) so I was trying to replace it in this repo: https://github.com/SE7ENSKY/jade2php/blob/master/src/jsExpressionToPhp.coffee#L24

**Comment by sstur** [comment]
My `js2php` might be a little heavyweight for what you're trying to do. It is designed to convert a set of statements rather than simply an expression. By heavyweight I mean it includes an entire runtime to handle things like object prototypes and to provide JavaScript's built-in methods and functions.

Furthermore, my `js2php` doesn't work the way `endel`'s `js2php` does. His is more of a syntax transform (which is probably closer to what you're after) whereas mine is meant to produce PHP code that is *functionally* equivalent (produces the same output as it's JS counterpart). Mine has other features such as extensibility (you can write modules to expose new functionality to the JS side, such as a database adapter) and out of the box my `js2php` produces php that is guaranteed to be safe to run on your server. By default it doesn't expose any way to access unsafe php functions from JS.

That being said, please have a look at the online demo:
http://sstur.github.io/js2php/demo/

If it does what you're after I can help you get the transform working from within Node.

**Comment by bfred-it** [comment]
Ah, I see. I might just be worth a try, though. I saw the demo but couldn't figure out its usage still so now I'm just using `variable['1']` :D

**Comment by sstur** [comment]
To transform some code from Node, you should be able to do something like:

    var transform = require('js2php/tools/transform');
    var php = transform({source: yourJavaScriptSource});
    // if you also want the runtime, use: transform.buildRuntime(options)
    var output = '<?php\n' + php + '\n';

the buildRuntime takes options like includeDebug: true, or log: someLogFunction but don't worry about that stuff unless you need it.
